return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "json",
      "javascript",
      "tsx",
      "yaml",
      "html",
      "css",
      "markdown",
      "svelte",
      "graphql",
      "bash",
      "lua",
      "vim",
      "dockerfile",
      "gitignore",
      "rust",
      "c_sharp",
      "go",
      "gomod",
      "gosum",
      "gowork",
      "yaml",
      "angular",
      "prisma",
    },
  },
}
